---
title: "Ph.D. project Deployment and Workflow"
output: html_document
---

This webpage has been created in order to present my Ph.D. project. The idea is to give some elements for a deeper understanding of the work that I've done in order to create my Ph.D. course admission project

## Title

"Heuristic perspective on learning and assessment of statistical reasoning:
an error-oriented point of view for educational purposes"

## Introduction: Two souls x Two souls

Scientific communication have an important role…

The CoVid-19 pandemic has shown the importance of scientific communication: scientific evidence has been used to drive normative regulamentation and individual behaviours during a world-wide crisis.   

During this life-changing period, on numerous occasions people were not able to properly communicate risks associated with health, nor to correctly interpret statistics about the CoronaVirus. 


This project has been elaborate in order to …



 … individuate cognitive flaws underlying our misinterpretation of statistical knowledge, in a learning perspective. The understanding of how our cognition generally fails to interprets numerical logic can enhance  our ability to teach students and people a less-flawed way to learn statistics, an approach that has been shown particularly effective in psychology.


```{r cars, message=FALSE, warning=FALSE, echo=FALSE}
library(tibble)
library(ggplot2)
data <- tibble(x= 1:100, y= 1:100)
data %>% 
  ggplot(aes(x, y)) +
  scale_x_continuous(minor_breaks = seq(10, 100, 10)) +
  scale_y_continuous(minor_breaks = seq(10, 100, 10)) +
  theme_linedraw()+
  geom_rect(xmin = 33, xmax=67, ymin=94, ymax=100, color='black',
            fill='white', size=0.25, size=0.25) +
  annotate('text', x= 50, y=97,label= 'Distortions of statistical reasoning', size=2.5) +
   geom_segment(
    x=40, xend=40, y=94, yend=81, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
    geom_segment(
    x=60, xend=60, y=94, yend=81, 
    size=0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 20, xmax=48, ymin=74, ymax=80, color='black',
            fill='white', size=0.25, size=0.25) +
  annotate('text', x= 34, y=77,label= 'Errors in learning (cognitive biases)', size=2.5) +
    geom_rect(xmin = 52, xmax=80, ymin=74, ymax=80, color='black',
            fill='white', size=0.25, size=0.25) +
  annotate('text', x= 66, y=77,label= 'Errors in assessment (misconceptions)', size=2.5) +
  theme_void()


```

